// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVUREmWlXl93kMDr6LeBpS_qS6oAHdXY',
    appId: '1:859608672558:web:fa94e96b85f5ecd65c72bf',
    messagingSenderId: '859608672558',
    projectId: 'wait-med-af648',
    authDomain: 'wait-med-af648.firebaseapp.com',
    storageBucket: 'wait-med-af648.firebasestorage.app',
    measurementId: 'G-BQLKLCEF5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5CoxmpT8T5T6z_IFtXBnOq7ky9tJLUs',
    appId: '1:859608672558:android:e24deb8317e92ced5c72bf',
    messagingSenderId: '859608672558',
    projectId: 'wait-med-af648',
    storageBucket: 'wait-med-af648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNftgANP42QaD8L4pncJ_onAPB-KJ49s',
    appId: '1:859608672558:ios:5d6e030e3ca2119c5c72bf',
    messagingSenderId: '859608672558',
    projectId: 'wait-med-af648',
    storageBucket: 'wait-med-af648.firebasestorage.app',
    iosBundleId: 'com.example.waitMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNftgANP42QaD8L4pncJ_onAPB-KJ49s',
    appId: '1:859608672558:ios:5d6e030e3ca2119c5c72bf',
    messagingSenderId: '859608672558',
    projectId: 'wait-med-af648',
    storageBucket: 'wait-med-af648.firebasestorage.app',
    iosBundleId: 'com.example.waitMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVUREmWlXl93kMDr6LeBpS_qS6oAHdXY',
    appId: '1:859608672558:web:d88438ae88ffaa525c72bf',
    messagingSenderId: '859608672558',
    projectId: 'wait-med-af648',
    authDomain: 'wait-med-af648.firebaseapp.com',
    storageBucket: 'wait-med-af648.firebasestorage.app',
    measurementId: 'G-N59XX5ZJYT',
  );

}