// main.dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Import Firebase Core
import 'firebase_options.dart'; // ✅ Generated by `flutterfire configure`

import 'package:wait_med/screens/account_settings_screen.dart';
import 'package:wait_med/screens/personal_details_screen.dart';
import 'package:wait_med/screens/home_screen.dart';
import 'package:wait_med/screens/map_screen.dart'; // Add this import
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/forgot_password_screen.dart';
import 'core/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase before running the app
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const WaitMedApp());
}

class WaitMedApp extends StatelessWidget {
  const WaitMedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "WaitMed",
      theme: AppTheme.lightTheme,
      initialRoute: '/',
      getPages: [
        GetPage(name: '/', page: () => const SplashScreen()),
        GetPage(name: '/login', page: () => const LoginScreen()),
        GetPage(name: '/register', page: () => const RegisterScreen()),
        GetPage(name: '/forgot', page: () => const ForgotPasswordScreen()),
        GetPage(name: '/home', page: () => const HomeScreen()),
        GetPage(name: '/account', page: () => const AccountSettingsScreen()),
        GetPage(name: '/personal', page: () => const PersonalDetailsScreen()),
        GetPage(
          name: '/map',
          page: () => const OpenStreetMapScreen(),
        ), // Add this route
      ],
    );
  }
}
